### ISSUE TITLE
Add link to http://cwohlman.github.io/KoGrid/  (your gh-pages)

### ISSUE THREAD

**Issue by yzorg** [cwohlman/KoGrid#4]
Nice improvements to KoGrid.  It took a while to find them via GH fork network graph.  Would have been nice if you added a section to your readme.md to link to your GH pages demo page.

http://cwohlman.github.io/KoGrid/

**Comment by cwohlman** [comment]
@yzorg  thanks for the suggestion, I'll be sure to do that.

**Comment by cwohlman** [comment]
How does the updated readme look now?
296060704725db7d0388ce6d01e2e5bb72a431ea

**Comment by yzorg** [comment]
Beauty.
